Petstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from account.views import register,MyLoginView,MyLogoutView
#from django.contrib.auth import views as auth_view
from petsapp.views import pets_list
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',pets_list,name='home'),
    path('petsapp/',include('petsapp.urls'),name='pets'),
    path('cart/',include('cart.urls'),name='cart'),
    path('orders/',include('orders.urls'),name='orders'),
    path('register/',register,name='register-page'),
    path('login/',MyLoginView.as_view(template_name='base/login.html'),name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('ordershistory/',views.orders_history,name='orders_history'),
]

if settings:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .import views
urlpatterns=[
    path('add_to_cart/<int:id>',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart_home,name='cart_home'),
    path('cartdelete/<int:id>',views.delete_cart_product,name='cart_delete'),
    path('updatecart/<int:id>/',views.update_cart,name="updatecart")
]

orders/urls.py
from django.urls import path
from .import views

app_name = "orders"
urlpatterns = [
    path('billing/',views.place_order,name='place_order'),
    path('payments/',views.payments,name='payments'),
   # path('orders_history/',views)
]

cart/models.py
from django.db import models
from petsapp.models import pet
from django.contrib.auth.models import User


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=300,blank=True)
    pet = models.ForeignKey(pet,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    totalprice = models.FloatField(default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'cart'

cart/views.py
from django.shortcuts import render,redirect
from petsapp.models import pet
from .models import Cart
from django.contrib import messages
from django.db.models import F ,Sum
from django.http import JsonResponse
# Create your views here.

def add_to_cart(request,id):
    cart_id = request.session.session_key
    if cart_id == None:
        cart_id = request.session.create()
        
        
    Pet = pet.objects.get(id=id)
    price = Pet.price
    user = request.user
    if Cart.objects.filter(user=user, pet=Pet).exists() :
        messages.error(request,"item already exist in the cart")
    else:
    
        Cart(cart_id=cart_id,pet=Pet,user=user,totalprice=price).save()
        messages.success(request,"Item Added to Cart Successfully")
    return redirect('/')
            
def cart_home(request):
    all_items = Cart.objects.filter(user=request.user)
    flag = all_items.exists()
    return render(request,'cart/cart_home.html',{'items':all_items,'flag':flag})

def update_cart(request,id):
    p = request.POST.get('price')
    q = request.POST.get('qnt')
    p_id = request.POST.get('id')
    totalPrice = float(p)*int(q)
    Cart.objects.filter(id=p_id).update(quantity=q,totalprice=totalPrice)
    total_amount = Cart.objects.filter(user=request.user).aggregate(total=Sum('totalprice'))['total']or 0.0
    
    return JsonResponse({'status':True,'totalprice':totalPrice,'total_amount':total_amount})
    
        
def delete_cart_product(request,id):
    cart = Cart.objects.get(id=id)
    cart.delete()
    messages.success(request,"Item Removed Successfully From Cart")
    return redirect('cart_home')

cart/templates/cart/cart_home.html
{% include 'base/header.html' %}
{% block content %}
    <form action="{% url 'orders:place_order' %}">
    <table class="table table-striped">
        <thead>
            <th scope="col">Pet name</th>
            <th scope="col">price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Price</th>
            <th scope="col">Action</th>
        </thead>
        {% if flag %}
        <tbody>
            {% for item in items %}
            <tr>
                <td><img src="{{ item.pet.image.url }}" alt="" width="100px" height="100px">
                    <h4>{{ item.pet.name }}</h4>
                </td>
                <td>{{ item.pet.price }}</td>
                <td>
                    <input type="number" name="qnt" min="0" value="{{ item.quantity }}" id = "quantity{{ item.id }}">
                </td>
                <td>
                    <input type="text" name="price" value="{{ item.totalprice }}" id="totalprice{{ item.id }}">

                </td>
                <td>
                    <a href="{% url 'cart_delete' item.id %}" class="btn btn-danger" data-id="{{ item.id }}">Delete</a>
                </td>
                
            </tr>
            {% endfor %}

        </tbody>
    {% else %}
        <h4>No Products Added in Cart ....</h4>
    {% endif %}
    </table>
    <h4>Total amount:<span id="totalamount">{{ totalamount }}</span></h4>

    <button type="submit">Proceed to pay</button>

    </form>
    <script>
        $(document).ready(function(){


            $('form').submit(function(e){
                e.preventDefault();
                var totalamount = parseFloat($("#totalamount").text()).toFixed(2);
                window.location.href = $(this).attr('action')+'?totalamount=' + totalamount ; 
            });


            localStorage.clear()  //local cache remove your data

            //Set quantity to 1 and update totalprice.

            $('input[name="qnt"]').each(function(){
                var id = $(this).closest('tr').find('a').data('id');
                var price = $(this).closest('tr').find('td:nth-child(2)').text()
                var totalprice = parseFloat(price)*1;
                $("#totalprice"+id).val(totalprice.toFixed(2));
                $(this).val(1);

            
            });


        //Calculate and Update the total amount

            function CalculateTotalAmount(){
                var totalamount = 0;
                $('input[name="qnt"]').each(function(){
                    var id = $(this).closest('tr').find('a').data('id');
                    var quantity = $(this).val();
                    var price = $(this).closest('tr').find('td:nth-child(2)').text()
                    var totalprice= parseFloat(price)*quantity;
                    $("#totalprice"+id).val(totalprice.toFixed(2));
                    totalamount += totalprice //totalamount = totalamount +totalprice
               
                });
                $("#totalamount").text(totalamount.toFixed(2));
            }
            

            //updating quantity and total price
            $('input[name="qnt"]').change(function(){
                var quantity = $(this).val();
                var price = $(this).closest('tr').find('td:nth-child(2)').text();
                var id = $(this).closest('tr').find('a').data('id');

                $.ajax({
                    url:'/cart/updatecart/'+ id +'/',
                    method :'POST',
                    data:{'qnt':quantity,'price':price,'id':id,'csrfmiddlewaretoken':'{{ csrf_token }}'},
                    success: function(response){
                        $("#totalprice"+id).val(response.totalprice);
                        CalculateTotalAmount();
                        var totalamount = $("#totalamount").text()
                        sessionStorage.setItem('totalamount',totalamount); // to set session value


                    },
                    error:function(){
                        alert("some Issue in the code");
                    }
                });
            });

            //calculate and update the initial amount.
            CalculateTotalAmount();

        });
            
        

    </script>



{% endblock %}
{% include 'base/footer.html' %}